# Generated by Django 3.0 on 2019-12-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoptions',
            name='deposit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventoptions',
            name='main_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eventoptions',
            name='other_prices',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventoptions',
            name='transport',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventoptions',
            name='transport_size',
            field=models.IntegerField(null=True),
        ),
    ]
