# Generated by Django 3.0 on 2019-12-21 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.Profile'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
