# Generated by Django 3.0 on 2020-01-23 20:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique_partic',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'event')},
        ),
    ]
