# Generated by Django 3.0 on 2019-12-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20191210_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoptions',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventoptions',
            name='main_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventoptions',
            name='other_prices',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventoptions',
            name='transport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventoptions',
            name='transport_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
