# Generated by Django 3.0 on 2020-01-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20200123_2330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_partic'),
        ),
    ]
