# Generated by Django 3.0 on 2019-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20191210_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='event',
            name='allow_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='allow_wife',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='for_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='main_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='need_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='other_prices',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='prepay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='transport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='transport_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventOptions',
        ),
    ]
