# Generated by Django 3.0 on 2019-12-11 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_auto_20191211_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 11, 19, 55, 23, 581789)),
        ),
    ]
