# Generated by Django 3.0 on 2019-12-11 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_auto_20191211_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 12, 11, 16, 56, 59, 329777, tzinfo=utc)),
        ),
    ]
